name: Hugging Face CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      HUGGING_FACE_TOKEN: ${{ secrets.HF_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort
      
      - name: Login to Hugging Face Hub
        run: |
          python -c "from huggingface_hub import login; login('${{ secrets.HF_TOKEN }}')"
      
      - name: Run code formatting check
        run: |
          black --check .
          isort --check-only --profile black .
      
      - name: Run tests with coverage
        run: |
          pytest --cov=./ --cov-report=xml
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
      
      - name: Build model artifacts
        run: |
          # Add your model training or packaging commands here
          echo "Building model artifacts..."
          # Example: python scripts/train_model.py
      
      - name: Push model to Hugging Face Hub
        if: github.event_name != 'pull_request'  # Only push on main branch, not PRs
        run: |
          # Add your model upload commands here
          echo "Pushing model to Hugging Face Hub..."
          # Example: python scripts/upload_model.py --token $HUGGING_FACE_TOKEN
